# Generated by Django 3.1.7 on 2021-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
                ('cid', models.IntegerField()),
                ('bal', models.FloatField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
